/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    VarBackTop: typeof import('@varlet/ui')['_BackTopComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCollapse: typeof import('@varlet/ui')['_CollapseComponent']
    VarCollapseItem: typeof import('@varlet/ui')['_CollapseItemComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarSlider: typeof import('@varlet/ui')['_SliderComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTooltip: typeof import('@varlet/ui')['_TooltipComponent']
  }
}
