interface SvgoPluginsDataList {
  id: string
  name: string
  active: boolean
  isCustom?: boolean
  description?: string
  isDefault?: boolean
}


export const SvgoPlugins: SvgoPluginsDataList[] = [
  {
    id: 'removeDoctype',
    name: '移除DOCTYPE',
    active: true,
    isDefault: true,
    description: '删除 <!DOCTYPE html PUBLIC "...">',
  },
  {
    id: 'removeXMLProcInst',
    name: '移除XML声明',
    active: true,
    isDefault: true,
    description: '移除 <?xml version="1.0" encoding="UTF-8"?>',
  },
  {
    id: 'removeComments',
    name: '移除注释',
    active: true,
    isDefault: true,
    description: '删除 XML 注释',
  },
  {
    id: 'removeMetadata',
    name: '移除<metadata>',
    active: true,
    isDefault: true,
    description: '移除 <metadata>',
  },
  {
    id: 'removeEditorsNSData',
    name: '移除编辑器数据',
    active: true,
    isDefault: true,
    description: '移除编辑软件相关的所有 XML 命名空间、元素和属性',
  },
  {
    id: 'cleanupAttrs',
    name: '清除属性空格',
    active: true,
    isDefault: true,
    description: '从属性值中删除多余的空格',
  },
  {
    id: 'mergeStyles',
    name: '合并样式',
    active: true,
    isDefault: true,
    description: '将多个 <style> 元素合并为一个',
  },
  {
    id: 'inlineStyles',
    name: '内联样式',
    active: true,
    isDefault: true,
    description: '将 <style> 元素的样式合并到匹配元素的 style 属性中',
  },
  {
    id: 'minifyStyles',
    name: '压缩<style>',
    active: true,
    isDefault: true,
    description: '使用 CSSO 缩小 <style> 元素',
  },
  {
    id: 'cleanupIds',
    name: '清除ID',
    active: true,
    isDefault: true,
    description: '删除未使用的 ID，并最小化其他元素引用的 ID',
  },
  {
    id: 'removeUselessDefs',
    name: '移除无用的<defs>',
    active: true,
    isDefault: true,
    description: '删除 <defs> 中未被引用的子元素',
  },
  {
    id: 'cleanupNumericValues',
    name: '数值四舍五入',
    active: true,
    isDefault: true,
    description: '对数值进行四舍五入，并在单位为 px 时删除单位',
  },
  {
    id: 'convertColors',
    name: '压缩色值',
    active: true,
    isDefault: true,
    description: '将颜色值转换为最短的等效值',
  },
  {
    id: 'removeUnknownsAndDefaults',
    name: '移除未知值和默认值',
    active: true,
    isDefault: true,
    description: '删除未知元素和属性，以及设置为其默认值的属性',
  },
  {
    id: 'removeNonInheritableGroupAttrs',
    name: '移除不可继承的<g>属性',
    active: true,
    isDefault: true,
    description: '从 <g> 中删除不可继承的属性',
  },
  {
    id: 'removeUselessStrokeAndFill',
    name: '移除无用的 stroke/fill',
    active: true,
    isDefault: true,
    description: '删除无用的 stroke 和 fill 属性, 例如 stroke-width="0" 或 stroke-opacity="0" 的时候',
  },
  {
    id: 'removeViewBox',
    name: '移除 viewBox',
    active: true,
    isDefault: true,
    description: '仅当 <svg> 标签存在 width 和 height 属性, 并且 viewBox="[0 0 width height]" 时, 才会移除 viewBox 属性',
  },
  {
    id: 'cleanupEnableBackground',
    name: '清理背景',
    active: true,
    isDefault: true,
    description: '清理 enable-background，除非文档使用 <filter> 元素',
  },
  {
    id: 'removeHiddenElems',
    name: '移除隐藏的元素',
    active: true,
    isDefault: true,
    description: '删除隐藏或不可见的元素, 可以是宽度和高度为 0 的元素，也可以是用 CSS 隐藏的元素',
  },
  {
    id: 'removeEmptyText',
    name: '移除空的<text>',
    active: true,
    isDefault: true,
    description: '删除空的 <text> 和 <tspan> 元素，以及不引用文档中其他节点的 <tref> 元素',
  },
  {
    id: 'convertShapeToPath',
    name: '基本形状转<path>',
    active: true,
    isDefault: true,
    description: '将基本形状转换为 <path> 元素',
  },
  {
    id: 'convertEllipseToCircle',
    name: '<ellipse>转<circle>',
    active: true,
    isDefault: true,
    description: '将非偏心 <ellipse> 元素转换为 <circle> 元素',
  },
  {
    id: 'moveElemsAttrsToGroup',
    name: '移动元素属性到<g>',
    active: false,
    isDefault: true,
    description: '将 <g> 内子元素公共属性移动到 <g> 标签',
  },
  {
    id: 'moveGroupAttrsToElems',
    name: '移动<g>属性到元素',
    active: true,
    isDefault: true,
    description: '移动 <g> 的 transform 属性到元素',
  },
  {
    id: 'collapseGroups',
    name: '折叠<g>',
    active: true,
    isDefault: true,
    description: '找到实际上不执行任何操作的组并将其扁平化，保留组的内容',
  },
  {
    id: 'convertPathData',
    name: '转换路径数据',
    active: true,
    isDefault: true,
    description: '优化 <path>、<glyph> 和 <missing-glyph> 元素中找到的路径命令',
  },
  {
    id: 'convertTransform',
    name: '转换 transform',
    active: true,
    isDefault: true,
    description: '将多个 transform 合并为一个，将矩阵转换为短别名等等',
  },
  {
    id: 'removeEmptyAttrs',
    name: '移除空属性',
    active: true,
    isDefault: true,
    description: '从元素中删除空属性',
  },
  {
    id: 'removeEmptyContainers',
    name: '移除空容器',
    active: true,
    isDefault: true,
    description: '删除文档中没有子元素或有意义的属性的容器元素，不包括被忽略的 <svg> 元素',
  },
  {
    id: 'removeUnusedNS',
    name: '移除未使用的命名空间',
    active: true,
    isDefault: true,
    description: '仅删除顶层 <svg> 元素未使用的命名空间',
  },
  {
    id: 'mergePaths',
    name: '合并<path>',
    active: true,
    isDefault: true,
    description: '将多个 <path> 合并为一个',
  },
  {
    id: 'sortAttrs',
    name: '属性排序',
    active: true,
    isDefault: true,
    description: '对所有元素的属性进行排序',
  },
  {
    id: 'sortDefsChildren',
    name: '<defs>子元素排序',
    active: true,
    isDefault: true,
    description: '对 <defs> 所有子元素进行排序',
  },
  {
    id: 'removeTitle',
    name: '移除<title>',
    active: true,
    isDefault: true,
    description: '移除 <title> 标签, 移除之后可以在鼠标 hover 时不显示信息',
  },
  {
    id: 'removeDesc',
    name: '移除<desc>',
    active: true,
    isDefault: true,
    description: '仅当 <desc> 元素为空或者只包含编辑者信息时删除',
  },
  // 非默认
  {
    id: 'removeDimensions',
    name: '删除尺寸',
    active: true,
    isDefault: false,
    description: '仅当 viewBox 属性存在时从 <svg> 元素中删除 width 和 height 属性, 如果缺少 viewBox, 则将其替换为 viewBox="0 0 width height"',
  },
  {
    id: 'removeStyleElement',
    name: '移除<style>',
    active: false,
    isDefault: false,
    description: '移除所有 <style> 元素',
  },
  {
    id: 'removeScriptElement',
    name: '移除<script>',
    active: false,
    isDefault: false,
    description: '移除所有 <script> 元素',
  },
  {
    id: 'convertStyleToAttrs',
    name: '转换样式为属性',
    active: true,
    isDefault: false,
    description: '将 <style> 中的表示属性转换为等效的 XML 属性',
  },
  {
    id: 'removeRasterImages',
    name: '移除内联图像',
    active: false,
    isDefault: false,
    description: '删除内联 JPEG、PNG 和 GIF',
  },
  {
    id: 'cleanupListOfValues',
    name: '清理值列表',
    active: false,
    isDefault: false,
    description: '对属性中的数值进行四舍五入, 例如 viewBox, enable-background, points',
  },
  {
    id: 'removeXMLNS',
    name: '移除xmlns',
    active: false,
    isDefault: false,
    description: '移除 <svg> 标签上的 xmlns 属性',
  },
  {
    id: 'removeXlink',
    name: '移除XLink命名空间前缀',
    active: false,
    isDefault: false,
    description: '删除 XLink 的所有应用, 并将部分 Xlink 引用转换为 SVG 原生属性, 例如: xlink:href -> href',
  },
  // 自定义
  {
    id: 'cleanupFill',
    name: '清理fill',
    active: true,
    isCustom: true,
    description: '移除已有 fill 属性, 并且为 <svg> 标签添加 fill="currentColor"',
  },
  {
    id: 'cleanupStroke',
    name: '清理stroke',
    active: true,
    isCustom: true,
    description: '重置 stroke 属性为 stroke="currentColor"',
  },
  {
    id: 'resetViewBox',
    name: '重置viewBox',
    active: false,
    isCustom: true,
    description: '重置 viewBox 属性为 [0 0 1024 1024], 仅当存在 <path> 时生效, 且 stroke 会导致结果异常',
  },
]
