name: Build/release

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
        
      - name: Publish Electron App
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
