name: Build/release


on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ windows-latest ]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
        
      - name: Publish Electron App
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
#      - name: Cleanup Artifacts for Windows
#        if: matrix.os == 'windows-latest'
#        run: |
#          npx rimraf "dist/!(*.exe)"
#
#      - name: Cleanup Artifacts for MacOS
#        if: matrix.os == 'macos-latest'
#        run: |
#          npx rimraf "dist/!(*.dmg)"

#      - name: upload artifacts
#        uses: actions/upload-artifact@v3.0.0
#        with:
#          name: ${{ matrix.os }}
#          path: out/make

#      - name: release
#        uses: softprops/action-gh-release@v0.1.14
#        if: startsWith(github.ref, 'refs/tags/')
#        with:
#          files: "dist/**"
#        env:
#          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
