name: Build/release

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    
    steps:
      # https://github.com/electron/forge/issues/3371
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: setup appdmg
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install python-setuptools
          npm install -g appdmg@0.6.6
      
      - name: Check out Git repository
        uses: actions/checkout@v4
      
      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: npm install
        
      - name: Publish Electron App
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
